SHELL  = /bin/sh

# seems that g++ (2.7.2) generates better warnings, but CC is much faster.

# for g++ on the DECs, HPs, SGIs, and Linux PCs use
CC     = g++
CFLAGS = -g -Wall

# for CC on the SGIs, use
# CC     = CC
# CFLAGS = -fullwarn

# command to use for making dependencies.
# (CC on SGIs doesn't do that, as far as I know.)
CCMD = g++

YO     = Output.your
YC     = Output.correct

# in SO, list a .o file for each .cc file, except for main.cc,
# that you want compiled and linked.
# if you have additional .cc files in this directory, that's generally fine;
# their dependencies will be included at the end of this Makefile,
# but they won't be compiled and linked.
SO = Number.o \
     Integer.o \
     Float.o \
     Complex.o  \
     Complex_Integer.o \
     Complex_Float.o \
     List.o \
     ListIt.o

.SUFFIXES : .o .cc

.cc.o :
	$(CC) $(CFLAGS) -c $<

a.out:	$(SO) main.o
	$(CC) $(CFLAGS) $(SO) main.o

# invoke via "make run" to run and compare output with correct output.
run: a.out
	./a.out 2>&1 > $(YO)
	diff $(YC) $(YO)

# invoke via "make clean".
clean:
	/bin/rm -f *.o *~ core a.out $(YO)

# just do `make remake' instead of `make clean; make'
remake:	clean a.out

# just do `make rerun' instead of `make remake; make run'
rerun:	remake run

# recompute source file dependencies
# do a `make depend' whenever code/file organization changes;
# should generally do a `make remake' after `make depend'.
depend:
	sed '1,/^# >>DO NOT DELETE THIS LINE<< #/!d' Makefile	>  Makefile.new
	echo '#   "make depend" was last run:  '`date`		>> Makefile.new
	$(CCMD) -MM *.cc					>> Makefile.new
	mv Makefile Makefile.bak
	mv Makefile.new Makefile

##############################################################################
# The rest of this file is generated by `make depend'.
# Don't change it by hand!
##############################################################################

# >>DO NOT DELETE THIS LINE<< #
#   "make depend" was last run:  Wed Mar 28 14:12:17 PST 2001
Number.o: Number.cc Number.h
